/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
//    public String getGreeting() {
//        return "Hello World!";
//    }

    public static void main(String[] args) {

        if (args.length < 2 || args.length > 3) {
            System.out.println("Parâmetros incorretos.");
            return;
        }

        String forma = "";
        int dimensao1 = 0;
        int dimensao2 = 0;
        int contagemDimensao = 0;

        for (String arg : args) {
            try {
                if (contagemDimensao == 0) {
                    dimensao1 = Integer.parseInt(arg);
                } else {
                    dimensao2 = Integer.parseInt(arg);
                }
                contagemDimensao++;
            } catch (NumberFormatException e) {
                forma = arg;
            }
        }

        if (forma.equals("triangulo")) {
            for (int i = 1; i <= dimensao1; i++) {
                System.out.print(" ".repeat(dimensao1 - i));
                System.out.print("*".repeat(i));
                System.out.println();
            }
        }

        if (forma.equals("losango")) {
            int espaco = (dimensao1 - 1) / 2;
            int asterisco = 1;
            int contadorSuperior = (dimensao1 + 1) / 2;
            int contadorInferior = (dimensao1 - 1) / 2;

            for (int i = 1; i <= contadorSuperior; i++) {
                System.out.print(" ".repeat(espaco));
                System.out.print("*".repeat(asterisco));
                System.out.print(" ".repeat(espaco));
                if (i < contadorSuperior) {
                    asterisco += 2;
                    espaco -= 1;
                }
                System.out.println();
            }

            for (int i = 1; i <= contadorInferior; i++) {
                asterisco -= 2;
                espaco += 1;
                System.out.print(" ".repeat(espaco));
                System.out.print("*".repeat(asterisco));
                System.out.print(" ".repeat(espaco));
                System.out.println();
            }
        }

        if (forma.equals("retangulo")) {
            System.out.println("*".repeat(dimensao1));
            for (int i = 1; i <= dimensao2 - 2; i++) {
                System.out.print("*");
                System.out.print(" ".repeat(dimensao1 - 2));
                System.out.println("*");
            }
            System.out.println("*".repeat(dimensao1));
        }


        // System.out.println(new App().getGreeting());
    }
}
