/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    // Exibir o triângulo
    public String triangulo(int dimensao1) {
        String resultado = "";
        for (int i = 1; i <= dimensao1; i++) {
            resultado += " ".repeat(dimensao1 - i);
            resultado += "*".repeat(i);
            resultado += "\n";
        }
        return resultado;
    }

    // Exibir o losango
    public String losango(int dimensao1) {
        String resultado = "";
        int espaco = (dimensao1 - 1) / 2;
        int asterisco = 1;
        int contadorSuperior = (dimensao1 + 1) / 2;
        int contadorInferior = (dimensao1 - 1) / 2;

        for (int i = 1; i <= contadorSuperior; i++) {
            resultado += " ".repeat(espaco);
            resultado += "*".repeat(asterisco);
            resultado += " ".repeat(espaco);
            if (i < contadorSuperior) {
                asterisco += 2;
                espaco -= 1;
            }
            resultado += "\n";
        }

        for (int i = 1; i <= contadorInferior; i++) {
            asterisco -= 2;
            espaco += 1;
            resultado += " ".repeat(espaco);
            resultado += "*".repeat(asterisco);
            resultado += " ".repeat(espaco);
            resultado += "\n";
        }
        return resultado;
    }

    // Exibir o retângulo
    public String retangulo(int dimensao1, int dimensao2) {
        String resultado = "";
        resultado += "*".repeat(dimensao1) + "\n";
        for (int i = 1; i <= dimensao2 - 2; i++) {
            resultado += "*";
            resultado += " ".repeat(dimensao1 - 2);
            resultado += "*\n";
        }
        resultado += "*".repeat(dimensao1) + "\n";
        return resultado;
    }

    public static void main(String[] args) {

        // Verifica se o usuário informou 2 ou 3 parâmetros
        if (args.length < 2 || args.length > 3) {
            System.out.println("Parâmetros incorretos.");
            return;
        }

        // Define as variáveis principais
        String forma = "";
        int dimensao1 = 0;
        int dimensao2 = 0;
        int contagemDimensao = 0;

        // Atribui os argumentos inseridos pelo usuário (lista args), em qualquer ordem,
        // às respectivas variáveis
        for (String arg : args) {
            try {
                if (contagemDimensao == 0) {
                    dimensao1 = Integer.parseInt(arg);
                } else {
                    dimensao2 = Integer.parseInt(arg);
                }
                contagemDimensao++;
            } catch (NumberFormatException e) {
                forma = arg;
            }
        }

        // Exibe cada forma segundo os argumentos fornecidos.
        // Exibe uma mensagem de erro caso de acordo com cada caso.
        if (forma.equals("triangulo")) {
            if (dimensao1 > 2) {
                System.out.println(new App().triangulo(dimensao1));
            } else {
                System.out.println("Informe uma dimensão maior que 2.");
            }
        } else if (forma.equals("losango")) {
            if (dimensao1 >= 3 && dimensao1 % 2 == 1) {
                System.out.println(new App().losango(dimensao1));
            } else {
                System.out.println("É necessário informar um número ímpar maior ou igual a 3.");
            }
        } else if (forma.equals("retangulo")) {
            if (dimensao1 > 2 && dimensao2 > 2) {
                System.out.println(new App().retangulo(dimensao1, dimensao2));
            } else {
                System.out.println("Informe uma dimensão maior que 2.");
            }
        } else {
            System.out.println("Forma não encontrada: " + forma);
        }
    }
}
