/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        String[][] tabuleiro = new String[10][10];

        // Inicializa o tabuleiro com ponto
        for (int i = 0; i < tabuleiro.length; i++) {
            for (int j = 0; j < tabuleiro[i].length; j++) {
                tabuleiro[i][j] = ".";
                System.out.print(tabuleiro[i][j]);
            }
            System.out.println();
        }

        int navio = {5, 4, 3, 3, 2};
        String simboloNavio = {"P", "E", "C", "S", "N"};

        Random r = new Random();
        int escolheOrientacao = r.nextInt(2);
        int escolheNavio = r.nextInt(5);
        boolean verificaPosicao = false;
        
        while (verificaPosicao) {}
    }
}
