/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Random;
import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        String[][] tabuleiro = new String[10][10];

        // Inicializa o tabuleiro com ponto
        for (int i = 0; i < tabuleiro.length; i++) {
            for (int j = 0; j < tabuleiro[i].length; j++) {
                tabuleiro[i][j] = ".";
                System.out.print(tabuleiro[i][j]);
            }
            System.out.println();
        }

        int[] navio = {5, 4, 3, 3, 2};
        String[] simboloNavio = {"P", "E", "C", "S", "N"};

        Random r = new Random();
        int orientacao = r.nextInt(2);
        int linhaColuna = r.nextInt(10);
        int navioSelecionado = r.nextInt(5);
        String[] itensTabuleiro = new String[5];
        int itensContagem = 0;
        boolean verificaPosicao = false;
        

        if (orientacao == 0) {
            int valorInicial = r.nextInt(10 - navio[navioSelecionado]);
            for (int i = valorInicial; i < valorInicial+navio[navioSelecionado]; i++) {
                if (!tabuleiro[i].equals(".")) {
                    verificaPosicao = false;
                    break;
                }
            verificaPosicao = true;
            }
            if (verificaPosicao) {
                for (int i = valorInicial; i < valorInicial+navio[navioSelecionado]; i++) {
                    tabuleiro[i] = simboloNavio[navioSelecionado];
                }
                itensTabuleiro[itensContagem] = simboloNavio[navioSelecionado];
            }
        }

        for (int i = 0; i < tabuleiro.length; i++) {
            for (int j = 0; j < tabuleiro[i].length; j++) {
                System.out.print(tabuleiro[i][j]);
            }
            System.out.println();
        }

    }
}
